#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S4,     SONAR,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int OBSTACLE_SENSE = 20;   //these constants are set for my robot. Yours may be different.
int AVOIDANCE_RADIUS = 1700;  //1750
int FORWARD_VALUE = 5200;
int SPEED = 30;
float P = 2.5;//proportionality constant
float D = 0; //derivative constant


void turn_90_left()  //fix.........
{
	setMotorSpeed(right, 30);
	setMotorSpeed(left, -30);
while(getGyroHeading(gyro) > -90)
	{}
//	wait1Msec (550);
	setMotorSpeed(right, 0);
	setMotorSpeed(left, 0);

}

void avoid_obstacle(int encoder_read)    //this avoids the obstacle by making a circle around it. Values work for my
{                                      //but may need to be changed for yours.
	if (getUSDistance(SONAR) < OBSTACLE_SENSE)
	{
		resetMotorEncoder(left);
		resetMotorEncoder(right);
		turn_90_left();
		while(getMotorEncoder(left) < AVOIDANCE_RADIUS)
		{
			setMotorSpeed(right, 20);
			setMotorSpeed(left, 30);
		}
		turn_90_left();
		resetMotorEncoder(right);
		FORWARD_VALUE -= encoder_read + 1100;
	}
}

void forward()
{
	int correct = 0;
	int error = 0;
	resetMotorEncoder(right);
	while(getMotorEncoder(right) < FORWARD_VALUE)// - distance_travelled)
	{
		int encoder_value = getMotorEncoder(right);
		avoid_obstacle(encoder_value);   //called during forward routine where you are most likely

		error = getGyroHeading(gyro);
		correct = (P*error + D*error);

		setMotorSpeed(right, SPEED+correct);
		setMotorSpeed(left, SPEED-correct);
		writeDebugStreamLine("%d",error);
		//correct = 0;
	}
}

task main()
{

	forward();


}
